[atom]
id = "rust-atom"
version = "0.1.0"
propagate = true

[std]
features = ["lib"]

[backend.nix]
fetcher = "flake-lock"

[fetch.nixpkgs-atom]
name = "nixpkgs-atom"

[fetch.crane]
name = "crane"
type = "flake"

[fetch.rust-overlay]
name = "rust-overlay"
type = "flake"