[atom]
id = "rust-atom"
version = "0.1.0"
propagate = true
system = true
pkgs = true
lib = true

[backend.nix]
fetcher = "flake-lock"

[fetch.src]
name = "src"
type = "src"

[fetch.crane]
name = "crane"
type = "flake"

[fetch.rust-overlay]
name = "rust-overlay"
type = "flake"